# Add post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "message": "This is a test post",https://github.com/iyehuda/adavanced-app-dev-task-1/pull/9/conflict?name=requests.http&ancestor_oid=a6ed935eb71d47d304407b581332a208e59e48e9&base_oid=c6d08cd154ccc9aec3354cf54bb2db95d5bd5ce2&head_oid=8ffa71182114cfdb9cbb1b8ff7885c8afc5f64d0
    "sender": "testuser@example.com"
}

###

# Get all posts
GET http://localhost:3000/posts

###

# Get a single post by ID
GET http://localhost:3000/posts/6738b7b2944556561a86110a

###

# Get posts by sender
GET http://localhost:3000/posts?sender=testuser@example.com

###

# Update a post
PUT http://localhost:3000/posts/6738b7b2944556561a86110a
Content-Type: application/json

{
    "message": "This is a different post"
}

###

# Add comment to a post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "post": "6738b7b2944556561a86110a",
  "message": "This is a test comment",
  "sender": "commenter@example.com"
}

###

# Get all comments
GET http://localhost:3000/comments

###
# Get comments for a specific post
GET http://localhost:3000/comments?post=6738b7b2944556561a86110a

###
# Get comments by a specific sender
GET http://localhost:3000/comments?sender=charlie@example.com

###
# Get a single comment by ID
GET http://localhost:3000/comments/67390276d8eff8c8bf2b4a88
