# Add post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "message": "This is a test post",
    "sender": "testuser@example.com"
}

###

# Get all posts
GET http://localhost:3000/posts

###

# Get a single post by ID
GET http://localhost:3000/posts/6738b7b2944556561a86110a

###

# Get posts by sender
GET http://localhost:3000/posts?sender=testuser@example.com

###

# Update a post
PUT http://localhost:3000/posts/6738b7b2944556561a86110a
Content-Type: application/json

{
    "message": "This is a different post"
}

###

# Add comment to a post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "post": "6738b7b2944556561a86110a",
  "message": "This is a test comment",
  "sender": "commenter@example.com"
}

###

# Get all comments
GET http://localhost:3000/comments

###
# Get comments for a specific post
GET http://localhost:3000/comments?post=6738b7b2944556561a86110a

###
# Get comments by a specific sender
GET http://localhost:3000/comments?sender=charlie@example.com

###
# Get a single comment by ID
GET http://localhost:3000/comments/67390276d8eff8c8bf2b4a88