# Add post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "message": "This is a test post",
    "sender": "testuser@example.com"
}

###

# Get all posts
GET http://localhost:3000/posts

###

# Get a single post by ID
GET http://localhost:3000/posts/6738b7b2944556561a86110a

###

# Get posts by sender
GET http://localhost:3000/posts?sender=testuser@example.com
